urls:
    prod_url: 'https://wallet-api.pagsmile.com'
    dev_url: 'https://dev-wallet.pagsmile.com'

paths:
    #登录/注册
    #登录次数接口
    logintimes_path: '/api/v1/user/loginTimes'
    #密码登录接口
    loginPwd_path: '/api/v1/user/loginPassword'
    #用户登录（跳转登录页）
    login_path: '/api/v1/user/login'
    #忘记密码
    forgotpwd_path: '/api/v1/user/forgotPassword'
    #注册设置登录密码接口
    setpassword_path: '/api/v1/user/setPassword'
    #注册登录接口
    register_path: '/api/v1/user/login'

    #账单
    #账单列表页接口
    transactionList_path: '/api/v1/transaction/list'
    #账单详情接口
    transactiondetail_path: '/api/v1/transaction/detail'

    #维护用户信息
    #个人信息接口
    profile_path: '/api/v1/user_info/profile'
    #添加个人信息接口
    addprofile_path: '/api/v1/user_info/add_profile'
    #保存个人信息接口
    saveprofile_path: '/api/v2/wallet/user/profile_save'
    #重置支付密码接口
    resetwalletpwd_path: '/api/v1/wallet/resetPassword'
    #重置登录密码接口
    resetuserpwd_path: '/api/v1/user/resetPassword'
    #调用短信平台接口（登录页忘记密码、更新手机号、注册）
    sendsms_path: '/api/v2/wallet/sms_code/send'
    #忘记支付密码
    forgotPayPwdSMS_path: '/api/v1/sms/send_sms'

    #银行账户
    #银行账户列表页接口
    banklist_path: '/api/v1/user/bankList'
    #添加银行账户接口
    addbank_path: '/api/v2/meta/code'
    #新增银行账户接口
    confirmbankinfo_path: '/api/v1/user/addBankInfo'
    #删除银行账户接口
    deletebankinfo_path: '/api/v1/user/deleteBankInfo'

    #渠道/提现
    #渠道列表接口
    channellist_path: '/api/v1/conf/channelList'
    #选择渠道接口
    channel_path: '/api/v1/withdraw/info'
    #验证支付次数接口
    paytimes_path: '/api/v1/wallet/payTimes'
    #pix提现接口
    pixdirect_path: '/api/v1/withdraw/pixdirect'
    #bank transfer提现
    bankTransfer_path: '/api/v1/withdraw/bank_transfer'
    #墨西哥-SPEI提现
    SPEI_path: '/api/v2/withdraw/to_bank_transfer'

    #物料接口
    good_path: '/api/v2/goods/list'

head:
    headers:
        'content-type': 'application/json'
        'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'

data:
    brazil_logintimes:
        'json':
            "areaCode": "86"
            "phone": "15848900589"
    brazil_loginPwd:
        'json':
            "areaCode": "86"
            "bonusCode": ""
            "phone": "15848900589"
            "captchaId": ""
            "code": ""
            "password": "08b798781a80f134c8efb49b89f260b7"
    mexico_logintimes:
        'json':
            "areaCode": "52"
            "phone": "4211111112"
    mexico_loginPwd:
        'json':
            "areaCode": "52"
            "bonusCode": ""
            "phone": "4211111112"
            "captchaId": ""
            "code": ""
            "password": "08b798781a80f134c8efb49b89f260b7"
    transactionList:
        'payload':
            "date": "2023-05"
            "transactionStatus": "1"
            "transactionType": "1"
    channellist:
        'json':
            "channelType": 1
    addbank_brazil:
        'json':
            "code_types": [2]
    addbank_mexico:
        'json':
            "code_types": [3]
    brazil_bank:
        'json':
            "accountDigit": 1
            "accountNumber": "214124124"
            # 1 - checking, 2 - saving
            "accountType": 2
            "agency": "2412"
            "bankCode": "241"
            "beneficiaryName": "GUILHERME ALVES DE SOUZA"
            "documentId": "36855571816"
    mexico_bank:
        'json':
            "accountNumber": "646180137004400578"
            "accountType": 5
            "bankCode": "40030"
            "beneficiaryName": "jiafeng"
            "documentId": "HEGG560427MVZRRL01"
            "documentType": 4
    addprofile_brazil:
        'json':
            "name": "GUILHERME ALVES DE SOUZA"
            "documentId": "36855571816"
            "documentType": "1"
            "email": "jiafeng@q1.com"
            "cep": "12345666"
            "regAgreementStatus": 1
    addprofile_mexico:
        'json':
            "name": "jiafeng"
            "documentId": "HEGG560427MVZRRL01"
            "email": "jia@jia.com"
            "cep": "12340"
            "regAgreementStatus": 1
    saveprofile_brazil:
        'json1':
            "new_cep": "98765432"
        'json2':
            "new_email": "jiafeng@xcloudgame.com"
    saveprofile_mexico:
        'json1':
            "new_cep": "12345"
        'json2':
            "new_email": "jiafeng@xcloudgame.com"
    forgotPayPwdSMS_brazil:
        'json':
            "scene": 5
    forgotPayPwdSMS_mexico:
        'json':
            "scene": 5
    sendsms_brazil:
        'json':
            "area_code": "86"
            "phone": "15000000000"
            "platform": 1
            # 7 - change_password, 8 - register
            "scene": 7
    sendsms_mexico:
        'json':
            "area_code": "52"
            "phone": "4211111112"
            "platform": 1
            # 7 - change_password, 8 - register
            "scene": 7
    brazil_channel:
        'payload1':
            "channel": "pix"
        'payload2':
            "channel": "bank_transfer"
    mexico_channel:
        'json':
            # SPEI
            "channel": 5
    SPEI_withdraw:
        'fail':
            "amount": "15.00"
            #mock buid
            "buid": "12345"
            "password": "0cfbd4458ac60a27b2fdcf28672e3710"
    pixdirect:
        # 设置提现金额小于0.50，报错：The withdraw amount can't be lower than R$0.50
        'pass':
            "amount": 0.01
            "currency": "BRL"
            # 1 - CNPJ,  2 - CPF, 3 - EVP,  4 - PHONE, 5 - EMAIL
            "pixType": 5
            "pixVal": "f5d9b9d8-b449-49d8-837d-19654e9a639a"
            "password": "0f1df8ad4082ddd083cb5c269019c0ed"
        # 设置支付密码错误，报错：The password or account is incorrect. Please try again.
        'fail':
            "amount": 0.50
            "currency": "BRL"
            # 1 - CNPJ,  2 - CPF, 3 - EVP,  4 -PHONE, 5 - EMAIL
            "pixType": 5
            "pixVal": "1@1.1"
            "password": "d69d629a420eae33d481871a0d491f29"
    bankTransfer:
        'fail':
            "amount": 10.00
            "currency": "BRL"
            "password": "d69d629a420eae33d481871a0d491f29"
            #mock buid
            "buid": "12345"
    resetwalletpwd_brazil:
        'json':
            "password": "0f1df8ad4082ddd083cb5c269019c0ed"
            "confirmPassword": "0f1df8ad4082ddd083cb5c269019c0ed"
            "oldPassword": "0f1df8ad4082ddd083cb5c269019c0ed"
    resetwalletpwd_mexico:
        'json':
            "password": "0f1df8ad4082ddd083cb5c269019c0ed"
            "confirmPassword": "0f1df8ad4082ddd083cb5c269019c0ed"
            "oldPassword": "0f1df8ad4082ddd083cb5c269019c0ed"
    resetuserpwd_brazil:
        'json':
            "password": "08b798781a80f134c8efb49b89f260b7"
            "confirmPassword": "08b798781a80f134c8efb49b89f260b7"
            "oldPassword": "08b798781a80f134c8efb49b89f260b7"
    resetuserpwd_mexico:
        'json':
            "password": "08b798781a80f134c8efb49b89f260b7"
            "confirmPassword": "08b798781a80f134c8efb49b89f260b7"
            "oldPassword": "08b798781a80f134c8efb49b89f260b7"
    register:
        'json':
            "areaCode": "86"
            "bonusCode": ""
            "phone": ""
            "code": ""
            "platform": 1
            "scene": 8
            "source": ""
    setpassword:
        'json':
            "password": "08b798781a80f134c8efb49b89f260b7"
            "confirmPassword": "08b798781a80f134c8efb49b89f260b7"
